# services/pgadmin-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/instance: pgadmin
  ports:
  - port: 5050
    targetPort: 80
  type: ClusterIP