---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/instance: weaviate
  name: weaviate
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/instance: weaviate
  name: weaviate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: weaviate
subjects:
- kind: ServiceAccount
  name: weaviate