apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
data:
  # Base64 encoded postgres username, default is postgres
  pg-username: cG9zdGdyZXM=
  # Base64 encoded postgres password, default is difyai123456
  pg-password: ZGlmeWFpMTIzNDU2
  # Base64 encoded postgres port 5432
  pg-port: NTQzMg==
type: Opaque
