apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
data:
  # Base64 encoded redis username, default is empty
  redis-username: ''
  # Base64 encoded redis password, default is redis
  redis-password: ZGlmeS1yZWRpcw==
  # Base64 encoded redis port 6379
  redis-port: NjM3OQ==
type: Opaque
