---
# DIFY API SERVICE
apiVersion: v1
kind: Service
metadata:
  name: dify-plugin
spec:
  ports:
    - port: 5003
      targetPort: 5003
      protocol: TCP
      name: remote
    - port: 5002
      targetPort: 5002
      protocol: TCP
      name: server
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dify-plugin
    app.kubernetes.io/instance: dify-plugin